books/api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^books/$', views.BookList.as_view()),
    url(r'^books/(?P<pk>[0-9|a-zA-Z]+)$', views.BookDetail.as_view()),
    url(r'^issued/$', views.BooksIssuedList.as_view()),
    url(r'^issued/(?P<pk>[0-9]+)$', views.BooksIssuedDetail.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

books/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^register/$', views.register_book, name='register_book'),
    url(r'^issue-book/(?P<pk>\d+)/$', views.issue_book, name='issue_book'),
    url(r'^return-book/(?P<pk>\d+)/$', views.return_book, name='return_book'),
    url(r'^books-issued/$', views.books_issued_list, name='books_issued_list'),
    url(r'^index/search/$', views.search_book, name='search'),
    url(r'^$', views.user_login, name='login'),

   
]

ebook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('books.urls', namespace='books')),
    url(r'^api/', include('books.api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

admin.site.site_header = 'EBOOK SYS'

books/models.py
from django.db import models


class BookCategory(models.Model):
    category = models.CharField(max_length=50, unique=True)
    category_slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.category


class Book(models.Model):
    book_no = models.CharField(max_length=20, db_index=True, unique=True)
    title = models.CharField(max_length=50)
    category = models.ForeignKey(BookCategory, on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', blank=True)
    publisher = models.CharField(max_length=100, blank=True, null=True)
    available = models.BooleanField(default=True)
    count = models.PositiveIntegerField("Times Borrowed", default=0)
    date_recorded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.book_no)


class BooksIssued(models.Model):
    book = models.OneToOneField(Book, verbose_name="Book No")
    phone_no = models.CharField(max_length=13)
    reg_no = models.CharField(max_length=20)
    date_issued = models.DateTimeField(auto_now_add=True)
    # Will change latter after implementation
    return_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Books Issued'

    def __str__(self):
        return str(self.book)

books/forms.py
from django import forms
from books.models import Book, BooksIssued


class RegisterBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('book_no', 'title', 'category', 'author', 'publisher')


class IssueBookForm(forms.Form):
    book_no = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'readonly':'readonly'}))
    phone_no = forms.CharField(max_length=13, required=True)
    reg_no = forms.CharField(max_length=20, required=True)


class ReturnBookForm(forms.Form):
    book_no = forms.CharField(max_length=20)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


# import many books into the database from a csv file
# class ImportBooksForm(forms.ModelForm):
#     file_to_import = forms.FileField()
#
#     class Meta:
#         model = Book
#         fields = ('file_to_import', )
#
#     def save(self, commit=False, *args, **kwagrs):
#         form = ImportBooksForm()
#         file_csv = request.FILES('file_to_import')
#         data_file = open(file_csv, 'rb')
#         records = csv.reader(data_file)
#         for line in records:
#             self.book_no = line[1]
#             self.title = line[2]
#             self.category = line[3]
#             self.author = line[4]
#             self.publisher = line[5]
#             form.save()
#         data_file.close()





books/api/views.py
from rest_framework import generics
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from books.api.serializers import *
from books.models import *


# views for api
class BookList(generics.ListCreateAPIView):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BooksIssuedList(generics.ListCreateAPIView):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = BooksIssued.objects.all()
    serializer_class = BooksIssuedSerializer


class BooksIssuedDetail(generics.RetrieveUpdateDestroyAPIView):
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = BooksIssued.objects.all()
    serializer_class = BooksIssuedSerializer



books/views.py
from django.shortcuts import *
from books.forms import *
from django.db.models import Q
from books.models import *
from django.contrib.auth import *


def register_book(request):
    if request.method == 'POST':
        form = RegisterBookForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Book Saved Successfully!")
    else:
        form = RegisterBookForm()
    return render(request, 'register_book.html', {'form': form})


def issue_book(request, pk):
    book = Book.objects.get(pk=pk)
    book_no = book.book_no
    form_args = {'book_no': book_no, }
    if request.method == 'POST':
        form = IssueBookForm(request.POST, initial=form_args)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                issued_bk = BooksIssued.objects.create(
                    book=book,
                    phone_no=cd['phone_no'],
                    reg_no=cd['reg_no']
                )
                book.available = False
                issued_bk.save()
                book.save()
                return HttpResponse("book issued Successfully")

            except:

                return HttpResponse("Error! book already issued out.")
    else:
        form = IssueBookForm(initial=form_args)
    return render(request, 'issue_book.html', {'form': form, })


def books_issued_list(request):
    bks = BooksIssued.objects.all()
    return render(request, 'books_issued.html', {'bks': bks, })


def return_book(request, pk):
    # get issued book
    try:
        book = Book.objects.get(pk=pk)
        book_issued = BooksIssued.objects.get(book=book)
        book_issued.delete()
        book.available = True
        book.count += 1
        book.save()
        return HttpResponse("Book returned successfully.")
    except Exception as e:
        return HttpResponse("Error occurred book not returned")


def search_book(request):
    query = request.GET.get('q', '')
    if query:
        query_set = (
            Q(title__icontains=query) |
            Q(author__icontains=query) |
            Q(publisher__icontains=query) |
            Q(category__icontains=query)
            # Q(available=True)
        )
        results = Book.objects.filter(query_set).distinct()
    else:
        results = []
    return render_to_response('index.html', {'results': results, 'query': query, })


def index(request):
    available_books = Book.objects.filter(available=True)
    return render(request, 'index.html', {'books': available_books, })


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # get the cleaned data
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                # check if the user is active
                if user.is_active:
                    login(request, user)
                    # provide the login url for redirect
                    return HttpResponseRedirect('/index/')
                else:
                    return HttpResponse('Account is dissabled Contact Admin')
            else:
                return HttpResponse('Login Successful!')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form, })

books/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} E-Book Web {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!-- my local css and bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
     <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    
    <!--end of my local -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
        }

        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            margin-bottom: 0;

        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>


<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Logo</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav">

                <li class="active"><a href="{% url 'books:index' %}">Home</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Book Categories
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% block category %}

                            <li>No category available!</li>

                        {% endblock %}

                    </ul>
                </li>
                <li><a href="{% url 'books:index' %}">Books</a></li>
                <li><a href="{% url 'books:books_issued_list' %}">Books Issued</a></li>
                <li><a href="#">Create Account</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <!--<li><p>Logged in as </p></li>-->
                <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                    {% if user.is_authenticated %}

                        {{ request.user }}

                    {% endif %}</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        </div>
    </div>
</nav>


<div class="container">
    {% block content %}

    {% endblock %}
</div>

<div class="nav nav-bar-fixed bottom">
<footer class="container-fluid text-center fixed-bottom">

    <p>HuduTech-Solutions Copyright &copy;2016</p>

</footer>
</div>
</body>

books/templates/books_issued.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-striped">
        <thead>
        <td>#</td>
        <td>Book No</td>
        <td>Student Phone No</td>
        <td>Reg No</td>
        <td>Date Issued</td>
        <td></td>
        </thead>
        {% for b in bks %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ b.book.book_no }} </td>
                <td>{{b.phone_no }}</td>
                <td>{{b.reg_no }}</td>
                <td>{{ b.date_issued }}</td>
                <td><a href="{% url 'books:return_book' pk=b.book.pk %}" class="btn btn-danger">Return</a></td>
                <td>{{ b.date_issued }}</td>
            </tr>
        {% endfor %}

    </table>
    </div></div>
{% endblock %}

books/templates/import_books_csv.html
<form action="" method="post" enctype="multipart/form-data">
 {% csrf_token%}
  {{form.as_p}}
   <input type="submit" value="Import Csv File">
   
</form>

books/templates/index.html
{% extends 'base.html' %}
{% block content %}
<!-- search box-->
<form action="{% url 'books:search' %}" method="GET">
    <label for='q'> Search</label>
    <input type="text" name="q" value="{{ query | escape }}">
    <input type="submit" value="Search">
</form>

{% if query %}
    <h6>Showing Results For "{{ query|escape }}"</h6>

    {% if results %}
        {% for book in results %}
            <h3>{{ forloop.counter }} {{ book|escape }}</h3>
           <li><a href="{% url 'books:issue_book' pk=book.pk %}">Issue Out</a></li>

        {% endfor %}
    {% else %}
        <h6> No Match found</h6>
    {% endif %}

{% endif %}


<!--end of search-box-->


<h4>List of Available books</h4>
<ul>
    {% if books %}
    {% for bk in books%}
	<li><strong>{{bk.title}}</strong> by <i>{{bk.author}}</i></li>
    <li><a href="{% url 'books:issue_book' pk=bk.pk %}">Issue Out</a></li>
	{% endfor %}
	{%else %}
	<h5>No Book Available!</h5>
	{% endif %}
    

</ul>
{% endblock %}

books/templates/issue_book.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col col-md-6">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Issue Out" class="btn btn-success">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

books/templates/login.html
<form accept="{%url 'books:login'%}?"next="{{request.get_full_path}}" method="post">
	{% csrf_token %}
	{{form.as_p}}
<input type="submit" value="Login">
</form>

books/templates/register_book.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% block content %}
    <div class="row">
        <div class="container">
            <div class="col col-md-6">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Add Book" class="btn btn-success">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

books/templates/search.html
<!DOCTYPE html>
<html>
<head>
    <title>Search {% if query %}Results {% endif %}</title>
</head>
<body>
<form action="" method="GET">
    <label for='q'> Search</label>
    <input type="text" name="q" value="{{ query | escape }}">
    <input type="submit" value="Search">
</form>

{% if query %}
    <h6>Showing Results For "{{ query|escape }}"</h6>

    {% if results %}
        {% for book in results %}
            <h6>{{ forloop.counter }} {{ book|escape }}</h6>

        {% endfor %}
    {% else %}
        <h6> No Match found</h6>
    {% endif %}

{% endif %}

</body>
</html>